#!/usr/bin/env python3
"""Build lines.js from Ile-de-France Mobilites open data.

Source: https://data.iledefrance-mobilites.fr - dataset
"traces-du-reseau-ferre-idf" (1673 rows, no API key required).

One row is one run of track, tagged with the line it carries in the same
res_com format the station builder already parses ("METRO 1", "RER A"). We
keep the metro and RER rows and drop train/tram/VAL.

Raw geometry is 17k coordinates for 370 kB, which is a lot of file for a
detail nobody can see: the traces follow the tunnels curve by curve. They are
simplified with Douglas-Peucker at a tolerance of about 11 m - below what a
2.5 px line can show at the game's maximum zoom - which costs 80% of the
coordinates and none of the shape.

Run:  python3 build-lines.py
"""

import json
import math
import re
import urllib.parse
import urllib.request
from pathlib import Path

API = "https://data.iledefrance-mobilites.fr/api/explore/v2.1"
DATASET = "traces-du-reseau-ferre-idf"
PAGE = 100

KEEP_PREFIX = ("METRO", "RER")

# Degrees of latitude, so ~11 m. One rendered pixel at zoom 17 is about 1 m,
# but a 2.5 px stroke hides an order of magnitude more than that.
TOLERANCE_DEG = 1e-4


def fetch_all():
    rows, offset = [], 0
    while True:
        qs = urllib.parse.urlencode(
            {
                "limit": PAGE,
                "offset": offset,
                "select": "res_com,metro,rer,geo_shape",
                "where": "metro = 1 or rer = 1",
            }
        )
        with urllib.request.urlopen(f"{API}/catalog/datasets/{DATASET}/records?{qs}") as r:
            page = json.load(r)
        rows.extend(page["results"])
        total = page["total_count"]
        offset += PAGE
        if offset >= total:
            print(f"fetched {len(rows)}/{total} track segments")
            return rows


def parse_line(res_com):
    """'METRO 7bis' -> ('metro', '7bis'). None for anything we do not draw."""
    parts = (res_com or "").strip().split()
    if len(parts) < 2 or parts[0].upper() not in KEEP_PREFIX:
        return None
    return parts[0].lower(), " ".join(parts[1:])


def line_sort_key(kind, label):
    m = re.match(r"(\d+)(.*)", label)
    return (kind, int(m.group(1)), m.group(2)) if m else (kind, 99, label)


def perpendicular_km(p, a, b):
    """Distance from p to segment ab, in degrees-as-plane. Fine at this scale."""
    (x, y), (x1, y1), (x2, y2) = p, a, b
    dx, dy = x2 - x1, y2 - y1
    if dx == 0 and dy == 0:
        return math.hypot(x - x1, y - y1)
    t = max(0, min(1, ((x - x1) * dx + (y - y1) * dy) / (dx * dx + dy * dy)))
    return math.hypot(x - (x1 + t * dx), y - (y1 + t * dy))


def simplify(points, tolerance):
    """Douglas-Peucker. Keeps the ends and every corner worth more than tolerance."""
    if len(points) < 3:
        return points
    first, last = points[0], points[-1]
    index = max(range(1, len(points) - 1), key=lambda i: perpendicular_km(points[i], first, last))
    if perpendicular_km(points[index], first, last) > tolerance:
        return simplify(points[: index + 1], tolerance)[:-1] + simplify(points[index:], tolerance)
    return [first, last]


def build():
    segments, raw_points = [], 0
    for row in fetch_all():
        parsed = parse_line(row.get("res_com"))
        shape = (row.get("geo_shape") or {}).get("geometry") or {}
        if not parsed or shape.get("type") != "LineString":
            continue

        kind, label = parsed
        coords = shape["coordinates"]
        raw_points += len(coords)
        # GeoJSON is lon/lat; Leaflet wants lat/lon, so flip here rather than
        # making every caller remember.
        points = [
            [round(lat, 5), round(lon, 5)]
            for lon, lat in simplify([tuple(c) for c in coords], TOLERANCE_DEG)
        ]
        if len(points) > 1:
            segments.append({"kind": kind, "line": label, "pts": points})

    segments.sort(key=lambda s: line_sort_key(s["kind"], s["line"]))
    kept = sum(len(s["pts"]) for s in segments)
    print(f"simplified {raw_points} -> {kept} coordinates ({100 - kept * 100 // raw_points}% off)")
    return segments


def main():
    segments = build()
    labels = sorted({(s["kind"], s["line"]) for s in segments}, key=lambda kl: line_sort_key(*kl))
    print(f"{len(segments)} segments across {len(labels)} lines:")
    for kind in ("metro", "rer"):
        drawn = [label for k, label in labels if k == kind]
        print(f"  {kind}: {' '.join(drawn)}")

    out = Path(__file__).parent / "data" / "lines.js"
    payload = json.dumps(segments, ensure_ascii=False, separators=(",", ":"))
    out.write_text(
        "// Generated by build-lines.py - do not edit by hand.\n"
        "// Source: Ile-de-France Mobilites open data (ODbL). Points are [lat, lon].\n"
        f"window.LINES = {payload};\n",
        encoding="utf-8",
    )
    print(f"wrote {out} ({out.stat().st_size / 1024:.1f} kB)")


if __name__ == "__main__":
    main()
